# Generated by Django 5.0.4 on 2024-07-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberfee',
            name='name',
        ),
        migrations.AddField(
            model_name='memberfee',
            name='u_type',
            field=models.CharField(choices=[('student', 'Student'), ('official', 'Official')], default=66, max_length=10),
            preserve_default=False,
        ),
    ]
