# Generated by Django 5.0.4 on 2024-07-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_memberfee_name_memberfee_u_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentrecord',
            name='memberFee_id',
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='user_type',
            field=models.CharField(default=33, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='memberfee',
            name='u_type',
            field=models.CharField(choices=[('student', 'Student'), ('official', 'Official')], max_length=10, unique=True),
        ),
    ]
