# Generated by Django 5.0.4 on 2024-05-04 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.CharField(choices=[('vice_president', 'Vice President'), ('treasurer', 'Treasurer'), ('general_secretary', 'General Secretay')], max_length=25, unique=True)),
                ('uid', models.CharField(blank=True, max_length=20)),
                ('user_type', models.CharField(blank=True, choices=[('student', 'Student'), ('official', 'Official')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
