# Generated by Django 5.0.4 on 2024-06-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_usersrole_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/def.jpg', null=True, upload_to='profile_pictures/'),
        ),
    ]
